### ISSUE TITLE
Project Status: Still Alive!

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [dmnd/dedent#36]
👋 Hi all! I'm going to be helping out with maintenance of the project for a little while. Pinning this issue to explain project context & next steps.

## Project Context

The `dedent` package has been one of the more common, popular packages in the JS ecosystem for quite a while. Per [`dedent` package on npm](https://npmjs.com/package/dedent) there are >16 million downloads a week. Quite impressive given that the last published version was 6 years ago.

In the long term, https://github.com/tc39/proposal-string-dedent is mostly going to become the standard way to dedent strings in JavaScript. But even if that were to be ratified today, it'd be some time before all engines run by users supported it. So this `dedent` package is here to stay for a while.

Both this project's popularity and the presence of a TC39 proposal are strong indicators that dedenting strings is a common, important user need in JS development!

## Next Steps

Here's what I'm going to do with this repository:

- [x] Triage the open issues
- [x] Review the open PRs
- [x] Generally bump dev dependencies to their latest versions: #37
- [x] Switch from Flow to TypeScript: #51
- [x] Add in some more tooling (issue templates, allcontributors bot, etc.) from [template-typescript-node-package](https://github.com/JoshuaKGoldberg/template-typescript-node-package) : #55 

### Publishing New Versions

I'm going to try to publish a new beta version with changes that have been merged over the last few years. I'll try to tag it as a beta so folks can preview it. Just to be safe. #16

Update July 2nd, 2023: [`dedent@1.0.0`](https://www.npmjs.com/package/dedent/v/1.0.0) is published under the _`beta`_ tag. I'll promote it to stable next week.

Update July 10th, 2023: [`dedent@1.0.1`](https://www.npmjs.com/package/dedent/v/1.0.1) is published as stable. 🚀 

### Out of Scope

For now, adding any large new features to `dedent` is out of scope. This package is going to stay mostly as-is.

Bug fixes will of course be accepted & released.

---

Please do post feedback if you have any questions or suggestions. Cheers all! ❤️

**Comment by G-Rath** [comment]
@JoshuaKGoldberg I'd recommend adding a changelog, even if its manually maintained for now if you're not planning that many changes just to help people understand what v1 has actually changed.

**Comment by JoshuaKGoldberg** [comment]
Agreed! I'm planning on onboarding this repo to https://github.com/JoshuaKGoldberg/template-typescript-node-package's tooling, which includes changelog generation. 👍

**Comment by JoshuaKGoldberg** [comment]
Closing out now that #55 is merged. Cheers!
